apiVersion: 1

datasources:
  - name: Trino Bronze
    type: trino-datasource
    access: proxy
    url: http://trino:8080
    user: admin
    basicAuth: false
    jsonData:
      catalog: youtube_trends
      schema: bronze
    secureJsonData:
      password: admin
    isDefault: true

  - name: Trino Silver
    type: trino-datasource
    access: proxy
    url: http://trino:8080
    user: admin
    jsonData:
      catalog: youtube_trends
      schema: silver
    secureJsonData:
      password: admin

  - name: Trino Gold
    type: trino-datasource
    access: proxy
    url: http://trino:8080
    user: admin
    jsonData:
      catalog: youtube_trends
      schema: gold
    secureJsonData:
      password: admin